# Generated by Django 2.0.3 on 2018-03-23 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20180323_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
