# Generated by Django 2.0.3 on 2018-03-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_auto_20180323_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(default="Type and text like 'Hello'  ", max_length=250),
        ),
    ]
